version: "3"
services:
  grafana:
    image: grafana/grafana:5.1.0
    environment: 
      - GF_SERVER_ROOT_URL=http://localhost:
      - GF_SECURITY_ADMIN_PASSWORD=123456
      - TZ="America/Bahia"
    ports:
      - 3000:3000
    user: "104"
  mysql:
    container_name: mysqlcontainer
    image: mysql:5.7
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fiapdb
      MYSQL_USER: fiap
      MYSQL_PASSWORD: 123456
      TZ: "America/Bahia"
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    networks:
      - back-tier
    restart: always
